### ISSUE TITLE
Open Source license

### ISSUE THREAD

**Issue by cahfofpai** [techtino/slot-switcher_Droidian#1]
How about putting this project under an open source license? Then people would be officially allowed to reuse your project and improve it.

https://choosealicense.com is a simple resource which helps choosing a license.

The app you based your project on (https://github.com/ubports-xiaomi-sdm660/Switch-My-Slot-Ubuntu-Touch) is licensed under MIT. But you do not have to use the same license.

**Comment by techtino** [comment]
Added MIT license. Thanks for flagging!
